# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_product_new_name_idx_and_more"),
        ("shopfront", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentCart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="persistent_cart", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Persistent cart",
                "verbose_name_plural": "Persistent carts",
            },
        ),
        migrations.CreateModel(
            name="CategorySubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscribers", to="catalog.category"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="category_subscriptions", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "-created_at"], name="cat_sub_user_created_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "category"), name="unique_category_subscription_per_user")],
            },
        ),
        migrations.CreateModel(
            name="BrandSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscribers", to="catalog.brand"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="brand_subscriptions", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "-created_at"], name="brand_sub_user_created_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "brand"), name="unique_brand_subscription_per_user")],
            },
        ),
    ]
