# Generated by Django 5.2.11 on 2026-03-07 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-is_new', 'name', 'id'], name='product_new_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-is_promo', 'name', 'id'], name='product_promo_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'name', 'id'], name='product_price_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-is_new', 'name', 'id'], name='product_cat_new_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', '-is_new', 'name', 'id'], name='product_brand_new_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', '-is_new', 'name', 'id'], name='product_seller_new_idx'),
        ),
    ]
