# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_product_new_name_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="lead_time_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="min_order_qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("kind", models.CharField(choices=[("certificate", "Сертификат"), ("spec", "Спецификация"), ("pdf", "PDF"), ("other", "Прочее")], default="pdf", max_length=16)),
                ("file_url", models.URLField()),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="catalog.product")),
            ],
            options={"ordering": ["ordering", "id"]},
        ),
    ]
