# Generated by Django 5.2.11 on 2026-03-20 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_publication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'publication_status', '-updated_at'], name='product_seller_pub_upd_idx'),
        ),
    ]
