# Generated by Django 5.2.11 on 2026-03-07 11:16

import django_fsm
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fakeacquiringpayment_and_mir_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('delivering', 'В работе'), ('delivered', 'Выполнен'), ('canceled', 'Отменен'), ('changed', 'Изменен')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
