# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_discount_amount_alter_order_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="source_channel",
            field=models.CharField(choices=[("web", "Web"), ("twa", "Telegram Web App"), ("api", "API")], default="web", max_length=16),
        ),
        migrations.AddField(
            model_name="order",
            name="split_status",
            field=models.CharField(
                choices=[("single", "Single seller"), ("planned", "Split planned"), ("ready", "Split ready"), ("split", "Split executed")],
                default="single",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="OrderSellerSplit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seller_store_name", models.CharField(blank=True, default="", max_length=255)),
                ("items_count", models.PositiveIntegerField(default=0)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("ready", "Ready"), ("sent", "Sent")], default="planned", max_length=16)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="seller_splits", to="orders.order")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_seller_splits", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["seller", "-created_at"], name="order_split_seller_created_idx")],
                "constraints": [models.UniqueConstraint(fields=("order", "seller"), name="unique_seller_split_per_order")],
            },
        ),
    ]
