# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_metadata_and_seller_splits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_access_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="order",
            name="placed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="placed_orders", to=settings.AUTH_USER_MODEL),
        ),
    ]
