# Generated by Django 5.2.11 on 2026-03-10 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_delivery_method_pickup_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_order_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderclaim',
            name='seller_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('invoice', 'По счёту'), ('mir_card', 'Карта МИР'), ('online_card', 'Онлайн-оплата')], default='cash', max_length=16),
        ),
    ]
