from __future__ import annotations

from dataclasses import dataclass

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction

from catalog.models import Brand, Category, Color, Product, Tag


@dataclass(frozen=True)
class Pools:
    first: tuple[str, ...]
    second: tuple[str, ...]
    third: tuple[str, ...] | None = None


def _compose_name(index: int, pools: Pools, separator: str = " ") -> str:
    base = len(pools.first) * len(pools.second)
    if pools.third:
        a = index % len(pools.first)
        b = (index // len(pools.first)) % len(pools.second)
        c = (index // base) % len(pools.third)
        return f"{pools.first[a]}{separator}{pools.second[b]}{separator}{pools.third[c]}"
    a = index % len(pools.first)
    b = (index // len(pools.first)) % len(pools.second)
    return f"{pools.first[a]}{separator}{pools.second[b]}"


def _assign_names(queryset, field: str, pools: Pools, separator: str = " ") -> int:
    items = list(queryset.order_by("id"))
    changed = 0
    for idx, item in enumerate(items):
        new_value = _compose_name(idx, pools, separator=separator)
        if getattr(item, field) != new_value:
            setattr(item, field, new_value)
            changed += 1
    if changed:
        queryset.model.objects.bulk_update(items, [field], batch_size=500)
    return changed


class Command(BaseCommand):
    help = (
        "Makes names human-friendly and unique without digits for products, tags, categories, "
        "brands, colors and usernames."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Preview how many rows would be changed without writing to DB.",
        )

    def handle(self, *args, **options):
        product_pools = Pools(
            first=(
                "Янтарный",
                "Лесной",
                "Северный",
                "Южный",
                "Горный",
                "Тёплый",
                "Мягкий",
                "Золотой",
                "Шёлковый",
                "Пряный",
                "Свежий",
                "Бархатный",
                "Лунный",
                "Солнечный",
                "Чистый",
                "Домашний",
                "Классический",
                "Винтажный",
                "Тихий",
                "Бодрый",
                "Сочный",
                "Плотный",
                "Нежный",
                "Лёгкий",
                "Крепкий",
                "Ровный",
                "Премиальный",
                "Фирменный",
                "Изысканный",
                "Уютный",
                "Искристый",
                "Радужный",
                "Ясный",
                "Гармоничный",
                "Карамельный",
                "Цитрусовый",
                "Ореховый",
                "Сливочный",
                "Медовый",
                "Травяной",
                "Лавандовый",
                "Утренний",
                "Вечерний",
                "Сказочный",
                "Благородный",
                "Смелый",
                "Яркий",
                "Мятный",
                "Румяный",
                "Купеческий",
                "Королевский",
                "Ремесленный",
                "Скандинавский",
                "Средиземный",
                "Традиционный",
                "Современный",
                "Авторский",
                "Ароматный",
                "Глубокий",
                "Тонкий",
                "Деликатный",
                "Праздничный",
                "Сезонный",
                "Морской",
                "Полевой",
                "Летний",
                "Осенний",
                "Зимний",
                "Весенний",
                "Кленовый",
                "Вишнёвый",
                "Гранатовый",
                "Персиковый",
                "Абрикосовый",
                "Черничный",
                "Клубничный",
                "Яблочный",
                "Грушевый",
                "Шафрановый",
                "Имбирный",
                "Ванильный",
                "Шоколадный",
                "Кофейный",
                "Чайный",
                "Ржаной",
                "Овсяный",
                "Миндальный",
                "Кокосовый",
                "Фисташковый",
            ),
            second=(
                "выбор",
                "букет",
                "вкус",
                "штрих",
                "акцент",
                "ритм",
                "тон",
                "баланс",
                "характер",
                "стиль",
                "подход",
                "резерв",
                "микс",
                "настрой",
                "заряд",
                "формула",
                "продукт",
                "вариант",
                "формат",
                "стандарт",
                "уровень",
                "комплект",
                "бриз",
                "поток",
                "вектор",
                "импульс",
                "профиль",
                "аромат",
                "рецепт",
                "купаж",
                "состав",
                "пакет",
                "путь",
                "маршрут",
                "вдох",
                "огонь",
                "луч",
                "мотив",
                "модуль",
                "версия",
                "традиция",
                "почерк",
                "форма",
                "линия",
                "сигнал",
                "контур",
                "набор",
                "этюд",
                "ансамбль",
                "градус",
                "простор",
                "горизонт",
                "сюжет",
                "драйв",
                "эталон",
                "класс",
                "потенциал",
                "признак",
                "символ",
                "маяк",
                "элемент",
                "момент",
                "деталь",
                "сценарий",
                "траектория",
                "конструкт",
                "рисунок",
                "колорит",
                "резонанс",
                "грация",
                "лидер",
                "оттенок",
                "компас",
                "взгляд",
                "экспрессия",
                "гарнитура",
                "серия",
                "релиз",
                "премьера",
                "рамка",
                "ракурс",
                "спектр",
                "кадр",
                "пульс",
                "ключ",
                "восход",
                "закат",
                "штиль",
                "парус",
            ),
        )

        tag_pools = Pools(
            first=(
                "Аромат",
                "Тепло",
                "Свежесть",
                "Нежность",
                "Крепость",
                "Лёгкость",
                "Сезон",
                "Выбор",
                "Вдохновение",
                "Традиция",
                "Настроение",
                "Смелость",
                "Комфорт",
                "Ритм",
                "Профиль",
                "Баланс",
                "Гармония",
                "Классика",
                "Деталь",
                "Контраст",
                "Колорит",
                "Акцент",
                "Вариант",
                "Рецепт",
                "Букет",
                "Почерк",
                "Сюжет",
                "Палитра",
                "Поток",
                "Линия",
                "Энергия",
                "Тонус",
                "Пульс",
                "Вектор",
                "Импульс",
                "Резонанс",
                "Эталон",
                "Мотив",
                "Купаж",
                "Штрих",
            ),
            second=(
                "утра",
                "дня",
                "вечера",
                "праздника",
                "дома",
                "леса",
                "сада",
                "лета",
                "осени",
                "зимы",
                "весны",
                "ветра",
                "солнца",
                "луны",
                "поля",
                "моря",
                "гор",
                "мастерской",
                "ярмарки",
                "легенды",
                "ремесла",
                "стиля",
                "вкуса",
                "аромата",
                "традиции",
                "сезона",
                "премьеры",
                "коллекции",
                "выбора",
                "гурмана",
                "гостя",
                "кухни",
                "пекарни",
                "кофейни",
                "чайной",
                "путешествия",
                "подарка",
                "встречи",
                "истории",
                "настроения",
            ),
        )

        category_pools = Pools(
            first=(
                "Кухонные",
                "Сервировочные",
                "Барные",
                "Кондитерские",
                "Чайные",
                "Кофейные",
                "Пекарские",
                "Домашние",
                "Праздничные",
                "Гастрономические",
                "Ремесленные",
                "Сезонные",
                "Подарочные",
                "Столовые",
                "Базовые",
                "Премиальные",
                "Повседневные",
                "Профессиональные",
                "Классические",
                "Авторские",
            ),
            second=(
                "решения",
                "коллекции",
                "наборы",
                "товары",
                "комплекты",
                "линейки",
                "инструменты",
                "аксессуары",
                "позиции",
                "форматы",
                "продукты",
                "варианты",
                "предложения",
                "серии",
                "направления",
                "категории",
                "подборки",
                "товары дня",
            ),
        )

        brand_pools = Pools(
            first=(
                "Северная",
                "Южная",
                "Горная",
                "Речная",
                "Лесная",
                "Медовая",
                "Лунная",
                "Солнечная",
                "Тихая",
                "Яркая",
                "Добрая",
                "Старая",
                "Новая",
                "Купеческая",
                "Городская",
                "Уютная",
                "Домашняя",
                "Пряная",
                "Винтажная",
                "Мастерская",
            ),
            second=(
                "лавка",
                "мастерская",
                "мануфактура",
                "коллекция",
                "линия",
                "фабрика",
                "галерея",
                "пекарня",
                "традиция",
                "студия",
                "верфь",
                "артель",
                "марка",
                "компания",
                "серия",
                "династия",
                "гильдия",
                "обитель",
                "палитра",
                "платформа",
            ),
        )

        color_pools = Pools(
            first=(
                "Тёплый",
                "Холодный",
                "Мягкий",
                "Глубокий",
                "Светлый",
                "Нежный",
                "Насыщенный",
                "Бархатный",
                "Пастельный",
                "Сочный",
                "Шёлковый",
                "Матовый",
                "Искристый",
                "Дымчатый",
                "Лёгкий",
                "Ясный",
                "Янтарный",
                "Лавандовый",
                "Морской",
                "Песочный",
            ),
            second=(
                "гранат",
                "рубин",
                "лазурит",
                "изумруд",
                "нефрит",
                "янтарь",
                "кварц",
                "топаз",
                "сапфир",
                "аметист",
                "коралл",
                "персик",
                "инжир",
                "карамель",
                "мята",
                "лимон",
                "океан",
                "графит",
                "мокко",
                "сливка",
            ),
        )

        username_pools = Pools(
            first=(
                "amber",
                "maple",
                "river",
                "cedar",
                "olive",
                "coral",
                "mint",
                "velvet",
                "sable",
                "silver",
                "golden",
                "honey",
                "cherry",
                "lunar",
                "solar",
                "forest",
                "meadow",
                "frost",
                "breeze",
                "willow",
                "hazel",
                "copper",
                "ivory",
                "cobalt",
                "scarlet",
                "pearl",
                "linen",
                "aurora",
                "aster",
                "birch",
                "dawn",
                "ember",
                "glade",
                "harbor",
                "juniper",
                "lotus",
                "misty",
                "noble",
                "opal",
                "poppy",
            ),
            second=(
                "falcon",
                "otter",
                "sparrow",
                "badger",
                "fox",
                "heron",
                "wren",
                "rook",
                "lynx",
                "kite",
                "alpaca",
                "robin",
                "orca",
                "beacon",
                "voyager",
                "artisan",
                "harvest",
                "keeper",
                "ranger",
                "sailor",
                "stargazer",
                "weaver",
                "pioneer",
                "guardian",
                "crafter",
                "walker",
                "sprinter",
                "navigator",
                "scholar",
                "maker",
                "seeker",
                "anchor",
                "bard",
                "carver",
                "dreamer",
                "editor",
                "forager",
                "grove",
                "horizon",
                "insight",
            ),
            third=(
                "atlas",
                "bloom",
                "crest",
                "drift",
                "echo",
                "flair",
                "glow",
                "haven",
                "isle",
                "jewel",
                "keel",
                "lumen",
                "mirth",
                "north",
                "orbit",
                "pulse",
                "quest",
                "ridge",
                "spruce",
                "trail",
            ),
        )

        dry_run = options["dry_run"]
        with transaction.atomic():
            changed = {
                "products": _assign_names(Product.objects, "name", product_pools),
                "tags": _assign_names(Tag.objects, "name", tag_pools),
                "categories": _assign_names(Category.objects, "name", category_pools),
                "brands": _assign_names(Brand.objects, "name", brand_pools),
                "colors": _assign_names(Color.objects, "name", color_pools),
                "users": _assign_names(get_user_model().objects, "username", username_pools, separator="_"),
            }
            if dry_run:
                transaction.set_rollback(True)
        self.stdout.write(self.style.SUCCESS(f"Updated: {changed}"))
