from django.urls import path, include
from .views.auth_html import (
    login_view, register_view, logout_view, telegram_webapp_login, confirm_email_view,
    validate_login_form, validate_register_form,
)
from .views.account_html import (
    account_home, account_addresses, account_legal_entities, account_orders, account_order_detail, account_comments,
    account_order_approval_action,
    account_order_cancel, account_order_reorder, account_order_invoice, account_order_tracking, account_approvals,
    account_order_claim_create, account_order_support_create, account_order_retry_payment,
    account_notifications, account_preferences, account_marketplace_ops,
    cancel_legal_request,
    account_company_members,
)
from .views.seller_html import (
    account_seller_home, account_seller_product_add, account_seller_product_edit,
    account_seller_product_import_template, account_seller_product_export,
    account_seller_orders, account_seller_order_detail, account_seller_order_status_action, account_seller_shipment_update,
    account_seller_shipment_create, account_seller_shipment_items_update, account_seller_order_item_cancel, account_seller_support_ticket_update, account_seller_claim_update,
    account_seller_offers, account_seller_offer_detail, account_seller_inventory_delete, account_seller_inventory_adjust, account_seller_warehouses, account_seller_analytics, account_seller_payouts, account_seller_invoices,
    account_seller_questions, account_seller_question_answer,
    account_seller_reviews, account_seller_review_reply,
)

urlpatterns = [
    path("", account_home, name="account_home"),
    path("addresses/", account_addresses, name="account_addresses"),
    path("legal/", account_legal_entities, name="account_legal"),
    path("legal/request/<int:pk>/cancel/", cancel_legal_request, name="account_legal_cancel"),
    path("orders/", account_orders, name="account_orders"),
    path("orders/<int:order_id>/", account_order_detail, name="account_order_detail"),
    path("orders/<int:order_id>/approval/", account_order_approval_action, name="account_order_approval_action"),
    path("orders/<int:order_id>/cancel/", account_order_cancel, name="account_order_cancel"),
    path("orders/<int:order_id>/reorder/", account_order_reorder, name="account_order_reorder"),
    path("orders/<int:order_id>/invoice/", account_order_invoice, name="account_order_invoice"),
    path("orders/<int:order_id>/tracking/", account_order_tracking, name="account_order_tracking"),
    path("orders/<int:order_id>/claims/", account_order_claim_create, name="account_order_claim_create"),
    path("orders/<int:order_id>/support/", account_order_support_create, name="account_order_support_create"),
    path("orders/<int:order_id>/retry-payment/", account_order_retry_payment, name="account_order_retry_payment"),
    path("approvals/", account_approvals, name="account_approvals"),
    path("notifications/", account_notifications, name="account_notifications"),
    path("preferences/", account_preferences, name="account_preferences"),
    path("marketplace/", account_marketplace_ops, name="account_marketplace_ops"),
    path("comments/", account_comments, name="account_comments"),
    path("legal/company/<int:company_id>/", account_company_members, name="account_company_members"),
    path("seller/", account_seller_home, name="account_seller_home"),
    path("seller/products/template/", account_seller_product_import_template, name="account_seller_product_import_template"),
    path("seller/products/export/", account_seller_product_export, name="account_seller_product_export"),
    path("seller/orders/", account_seller_orders, name="account_seller_orders"),
    path("seller/orders/<int:seller_order_id>/", account_seller_order_detail, name="account_seller_order_detail"),
    path("seller/orders/<int:seller_order_id>/status/", account_seller_order_status_action, name="account_seller_order_status_action"),
    path("seller/orders/<int:seller_order_id>/items/<int:item_id>/cancel/", account_seller_order_item_cancel, name="account_seller_order_item_cancel"),
    path("seller/orders/<int:seller_order_id>/support/<int:ticket_id>/", account_seller_support_ticket_update, name="account_seller_support_ticket_update"),
    path("seller/orders/<int:seller_order_id>/claims/<int:claim_id>/", account_seller_claim_update, name="account_seller_claim_update"),
    path("seller/orders/<int:seller_order_id>/shipments/create/", account_seller_shipment_create, name="account_seller_shipment_create"),
    path("seller/orders/<int:seller_order_id>/shipments/<int:shipment_id>/", account_seller_shipment_update, name="account_seller_shipment_update"),
    path("seller/orders/<int:seller_order_id>/shipments/<int:shipment_id>/items/", account_seller_shipment_items_update, name="account_seller_shipment_items_update"),
    path("seller/offers/", account_seller_offers, name="account_seller_offers"),
    path("seller/offers/<int:offer_id>/", account_seller_offer_detail, name="account_seller_offer_detail"),
    path("seller/warehouses/", account_seller_warehouses, name="account_seller_warehouses"),
    path("seller/analytics/", account_seller_analytics, name="account_seller_analytics"),
    path("seller/payouts/", account_seller_payouts, name="account_seller_payouts"),
    path("seller/invoices/", account_seller_invoices, name="account_seller_invoices"),
    path("seller/offers/<int:offer_id>/inventories/<int:inventory_id>/delete/", account_seller_inventory_delete, name="account_seller_inventory_delete"),
    path("seller/offers/<int:offer_id>/inventories/<int:inventory_id>/adjust/", account_seller_inventory_adjust, name="account_seller_inventory_adjust"),
    path("seller/questions/", account_seller_questions, name="account_seller_questions"),
    path("seller/questions/<int:question_id>/answer/", account_seller_question_answer, name="account_seller_question_answer"),
    path("seller/reviews/", account_seller_reviews, name="account_seller_reviews"),
    path("seller/reviews/<int:review_id>/reply/", account_seller_review_reply, name="account_seller_review_reply"),
    path("seller/products/add/", account_seller_product_add, name="account_seller_products_add"),
    path("seller/products/<int:product_id>/edit/", account_seller_product_edit, name="account_seller_product_edit"),
    path("login/", login_view, name="login"),
    path("login/validate/", validate_login_form, name="login_validate"),
    path("register/", register_view, name="register"),
    path("register/validate/", validate_register_form, name="register_validate"),
    path("confirm-email/", confirm_email_view, name="confirm_email"),
    path("logout/", logout_view, name="logout"),
    path("twa/login/", telegram_webapp_login, name="twa_login"),
    # allauth URLs under /account/social/
    path("social/", include("allauth.urls")),
]
