# Generated by Codex on 2026-03-09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0013_product_product_new_name_idx_and_more"),
        ("orders", "0008_guest_checkout_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("discount_type", models.CharField(choices=[("percent", "Percent"), ("fixed", "Fixed")], default="percent", max_length=16)),
                ("discount_value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("min_subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("customer_scope", models.CharField(choices=[("all", "All"), ("authenticated", "Authenticated only"), ("guest", "Guest only"), ("company", "Company only"), ("individual", "Individual only")], default="all", max_length=24)),
                ("stack_with_profile_discount", models.BooleanField(default=False)),
                ("brand", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotion_rules", to="catalog.brand")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotion_rules", to="catalog.category")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotion_rules", to="catalog.product")),
                ("seller", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotion_rules", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("per_user_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="coupons", to="promotions.promotionrule")),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="PromotionRedemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest_email", models.EmailField(blank=True, default="", max_length=254)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("coupon", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="promotions.coupon")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotion_redemptions", to="orders.order")),
                ("redeemed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotion_redemptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="promotionredemption",
            constraint=models.UniqueConstraint(fields=("coupon", "order"), name="unique_coupon_redemption_per_order"),
        ),
    ]
