# Generated by Django 5.2.11 on 2026-03-05 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_roles_status_lookups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_stores', to='commerce.legalentity')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Магазин продавца',
                'verbose_name_plural': 'Магазины продавцов',
            },
        ),
    ]
