# Generated by Django 5.2.11 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0006_legalentity_members_sellerstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerstore",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="seller_store_photos/"),
        ),
    ]
