# Generated by Django 5.2.11 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0007_sellerstore_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerstore",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
