# Generated by Codex on 2026-03-06

from django.db import migrations, models
from django.utils.text import slugify


def fill_sellerstore_slugs(apps, schema_editor):
    SellerStore = apps.get_model("commerce", "SellerStore")
    for store in SellerStore.objects.all().iterator():
        if store.slug:
            continue
        base = slugify(store.name) or f"store-{store.owner_id or 'x'}"
        candidate = base
        suffix = 2
        while SellerStore.objects.filter(slug=candidate).exclude(pk=store.pk).exists():
            candidate = f"{base}-{suffix}"
            suffix += 1
        store.slug = candidate
        store.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0008_sellerstore_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerstore",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True, null=True),
        ),
        migrations.RunPython(fill_sellerstore_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sellerstore",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
