# Generated by Django 5.2.11 on 2026-03-07 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_sellerstore_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='members',
            field=models.ManyToManyField(related_name='legal_entities', through='commerce.LegalEntityMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerstore',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255, unique=True),
        ),
    ]
