# Generated by Django 5.2.11 on 2026-03-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_approvalpolicy_required_approvals_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='preferred_payment_method',
            field=models.CharField(blank=True, default='invoice', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='procurement_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sellerstore',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerstore',
            name='moderation_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('role', models.CharField(choices=[('procurement', 'Закупки'), ('finance', 'Финансы'), ('receiving', 'Приёмка'), ('other', 'Прочее')], default='procurement', max_length=24)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='commerce.company')),
            ],
            options={
                'ordering': ['-is_default', 'name', 'id'],
            },
        ),
    ]
