# Generated by Django 5.2.11 on 2026-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_company_invoice_email_company_payment_comment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['legal_entity', 'is_default'], name='delivery_addr_default_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['legal_entity', '-updated_at'], name='delivery_addr_upd_idx'),
        ),
    ]
