from django.urls import path
from .views import (
    HomeView, CatalogView, ProductDetailView, TwaHomeView,
    AboutPageView, DeliveryPageView, ContactsPageView, BuyersPageView, SuppliersPageView, PaymentPageView, ReturnsPageView, FaqPageView,
    BrandsPageView, BrandLegacyRedirectView, BrandDetailPageView, CategoryDetailPageView, CollectionsPageView, CollectionDetailPageView, PromotionsPageView, BlogPageView,
    FavoritesPageView, FavoriteToggleView, SubscriptionToggleView, CompareToggleView, ComparePageView, SavedListsPageView, SavedListDetailView, SharedSavedListView, SavedListFromOrderView, SavedSearchesPageView,
    ProductPkRedirectView,
    LiveSearchView,
    ProductReviewUpsertView, ProductReviewDeleteView, ProductReviewVoteView, ProductQuestionCreateView,
    ProductReviewCommentCreateView, ProductReviewCommentUpdateView, ProductReviewCommentDeleteView,
    SellerStoreDetailView, SellerProfileView, SellerStoreLegacyRedirectView, SellerProfileLegacyRedirectView, StoreReviewUpsertView, StoreReviewDeleteView,
    FakePaymentPageView,
    FakePaymentEventView,
    GuestOrderDetailView,
    GuestFakePaymentPageView,
    GuestFakePaymentEventView,
    CartBadgeView, CartPanelView, CartAddView, BuyNowView, CartRemoveView, CartClearView, CartUpdateView, CartPageView,
    CheckoutPageView, CheckoutSubmitView,
    robots_txt, sitemap_xml,
)

urlpatterns = [
    path("robots.txt", robots_txt, name="robots_txt"),
    path("sitemap.xml", sitemap_xml, name="sitemap_xml"),
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("buyers/", BuyersPageView.as_view(), name="buyers"),
    path("suppliers/", SuppliersPageView.as_view(), name="suppliers"),
    path("delivery/", DeliveryPageView.as_view(), name="delivery"),
    path("payment/", PaymentPageView.as_view(), name="payment"),
    path("returns/", ReturnsPageView.as_view(), name="returns"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("faq/", FaqPageView.as_view(), name="faq"),
    path("brands/", BrandsPageView.as_view(), name="brands"),
    path("brands/<int:brand_id>/", BrandLegacyRedirectView.as_view(), name="brand_detail_legacy"),
    path("brands/<slug:brand_slug>/", BrandDetailPageView.as_view(), name="brand_detail"),
    path("catalog/categories/<slug:category_slug>/", CategoryDetailPageView.as_view(), name="category_detail"),
    path("collections/", CollectionsPageView.as_view(), name="collections"),
    path("collections/<slug:collection_slug>/", CollectionDetailPageView.as_view(), name="collection_detail"),
    path("promotions/", PromotionsPageView.as_view(), name="promotions"),
    path("blog/", BlogPageView.as_view(), name="blog"),
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("favorites/", FavoritesPageView.as_view(), name="favorites"),
    path("favorites/toggle/", FavoriteToggleView.as_view(), name="favorite_toggle"),
    path("subscriptions/toggle/", SubscriptionToggleView.as_view(), name="subscription_toggle"),
    path("compare/", ComparePageView.as_view(), name="compare_page"),
    path("compare/toggle/", CompareToggleView.as_view(), name="compare_toggle"),
    path("lists/", SavedListsPageView.as_view(), name="saved_lists"),
    path("lists/<int:list_id>/", SavedListDetailView.as_view(), name="saved_list_detail"),
    path("lists/shared/<slug:share_token>/", SharedSavedListView.as_view(), name="saved_list_shared"),
    path("lists/from-order/<int:order_id>/", SavedListFromOrderView.as_view(), name="saved_list_from_order"),
    path("saved-searches/", SavedSearchesPageView.as_view(), name="saved_searches"),
    path("search/live/", LiveSearchView.as_view(), name="live_search"),
    path("product/<int:pk>/", ProductPkRedirectView.as_view(), name="product_legacy_pk"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product"),
    path("product/<slug:slug>/review/", ProductReviewUpsertView.as_view(), name="product_review_upsert"),
    path("product/<slug:slug>/review/delete/", ProductReviewDeleteView.as_view(), name="product_review_delete"),
    path("product/<slug:slug>/review/<int:review_id>/vote/", ProductReviewVoteView.as_view(), name="product_review_vote"),
    path("product/<slug:slug>/review/<int:review_id>/comment/", ProductReviewCommentCreateView.as_view(), name="product_review_comment_create"),
    path("product/<slug:slug>/comment/<int:comment_id>/update/", ProductReviewCommentUpdateView.as_view(), name="product_review_comment_update"),
    path("product/<slug:slug>/comment/<int:comment_id>/delete/", ProductReviewCommentDeleteView.as_view(), name="product_review_comment_delete"),
    path("product/<slug:slug>/questions/", ProductQuestionCreateView.as_view(), name="product_question_create"),
    path("stores/<int:store_id>/", SellerStoreLegacyRedirectView.as_view(), name="seller_store_detail_legacy"),
    path("stores/<slug:store_slug>/", SellerStoreDetailView.as_view(), name="seller_store_detail"),
    path("stores/<slug:store_slug>/review/", StoreReviewUpsertView.as_view(), name="store_review_upsert"),
    path("stores/<slug:store_slug>/review/delete/", StoreReviewDeleteView.as_view(), name="store_review_delete"),
    path("sellers/<str:username>/legacy/", SellerProfileLegacyRedirectView.as_view(), name="seller_profile_legacy"),
    path("sellers/<slug:seller_slug>/", SellerProfileView.as_view(), name="seller_profile"),
    path("cart/badge/", CartBadgeView.as_view(), name="cart_badge"),
    path("cart/", CartPageView.as_view(), name="cart_page"),
    path("cart/panel/", CartPanelView.as_view(), name="cart_panel"),
    path("cart/add/", CartAddView.as_view(), name="cart_add"),
    path("buy-now/", BuyNowView.as_view(), name="buy_now"),
    path("cart/remove/", CartRemoveView.as_view(), name="cart_remove"),
    path("cart/clear/", CartClearView.as_view(), name="cart_clear"),
    path("cart/update/", CartUpdateView.as_view(), name="cart_update"),
    path("twa/", TwaHomeView.as_view(), name="twa_home"),
    path("checkout/", CheckoutPageView.as_view(), name="checkout"),
    path("checkout/submit/", CheckoutSubmitView.as_view(), name="checkout_submit"),
    path("checkout/success/<int:order_id>/<slug:token>/", GuestOrderDetailView.as_view(), name="guest_order_detail"),
    path("payments/fake/<int:order_id>/", FakePaymentPageView.as_view(), name="fake_payment_page"),
    path("payments/fake/<int:order_id>/event/", FakePaymentEventView.as_view(), name="fake_payment_event"),
    path("payments/fake/<int:order_id>/<slug:token>/", GuestFakePaymentPageView.as_view(), name="guest_fake_payment_page"),
    path("payments/fake/<int:order_id>/<slug:token>/event/", GuestFakePaymentEventView.as_view(), name="guest_fake_payment_event"),
]
