from django.urls import path
from .views import (
    HomeView, CatalogView, ProductDetailView, TwaHomeView,
    AboutPageView, DeliveryPageView, ContactsPageView,
    ProductPkRedirectView,
    LiveSearchView,
    ProductReviewUpsertView, ProductReviewDeleteView,
    ProductReviewCommentCreateView, ProductReviewCommentUpdateView, ProductReviewCommentDeleteView,
    SellerStoreDetailView, SellerProfileView,
    FakePaymentPageView,
    FakePaymentEventView,
    CartBadgeView, CartPanelView, CartAddView, CartRemoveView, CartClearView, CartUpdateView, CartPageView,
    CheckoutPageView, CheckoutSubmitView,
    robots_txt, sitemap_xml,
)

urlpatterns = [
    path("robots.txt", robots_txt, name="robots_txt"),
    path("sitemap.xml", sitemap_xml, name="sitemap_xml"),
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("delivery/", DeliveryPageView.as_view(), name="delivery"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("search/live/", LiveSearchView.as_view(), name="live_search"),
    path("product/<int:pk>/", ProductPkRedirectView.as_view(), name="product_legacy_pk"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product"),
    path("product/<slug:slug>/review/", ProductReviewUpsertView.as_view(), name="product_review_upsert"),
    path("product/<slug:slug>/review/delete/", ProductReviewDeleteView.as_view(), name="product_review_delete"),
    path("product/<slug:slug>/review/<int:review_id>/comment/", ProductReviewCommentCreateView.as_view(), name="product_review_comment_create"),
    path("product/<slug:slug>/comment/<int:comment_id>/update/", ProductReviewCommentUpdateView.as_view(), name="product_review_comment_update"),
    path("product/<slug:slug>/comment/<int:comment_id>/delete/", ProductReviewCommentDeleteView.as_view(), name="product_review_comment_delete"),
    path("stores/<int:store_id>/", SellerStoreDetailView.as_view(), name="seller_store_detail"),
    path("sellers/<str:username>/", SellerProfileView.as_view(), name="seller_profile"),
    path("cart/badge/", CartBadgeView.as_view(), name="cart_badge"),
    path("cart/", CartPageView.as_view(), name="cart_page"),
    path("cart/panel/", CartPanelView.as_view(), name="cart_panel"),
    path("cart/add/", CartAddView.as_view(), name="cart_add"),
    path("cart/remove/", CartRemoveView.as_view(), name="cart_remove"),
    path("cart/clear/", CartClearView.as_view(), name="cart_clear"),
    path("cart/update/", CartUpdateView.as_view(), name="cart_update"),
    path("twa/", TwaHomeView.as_view(), name="twa_home"),
    path("checkout/", CheckoutPageView.as_view(), name="checkout"),
    path("checkout/submit/", CheckoutSubmitView.as_view(), name="checkout_submit"),
    path("payments/fake/<int:order_id>/", FakePaymentPageView.as_view(), name="fake_payment_page"),
    path("payments/fake/<int:order_id>/event/", FakePaymentEventView.as_view(), name="fake_payment_event"),
]
