[project]
name = "bad-guys-bot"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
  "aiogram>=3.7",
  "fastapi>=0.115",
  "uvicorn>=0.30",
  "httpx>=0.27",
  "python-dotenv>=1.0",
  "prometheus-client>=0.20"
]

[tool.uv]
dev-dependencies = ["pytest", "ruff", "mypy"]
