# Generated by Django 5.2.11 on 2026-03-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_account_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('manager', 'Менеджер'), ('client', 'Клиент'), ('seller', 'Продавец')], default='client', max_length=16),
        ),
    ]
