# Generated by Codex on 2026-03-06

from django.db import migrations, models
from django.utils.text import slugify


def fill_profile_slugs(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    for profile in UserProfile.objects.select_related("user").all().iterator():
        if profile.slug:
            continue
        source = profile.full_name or profile.user.username or f"user-{profile.user_id}"
        base = slugify(source) or f"user-{profile.user_id or 'x'}"
        candidate = base
        suffix = 2
        while UserProfile.objects.filter(slug=candidate).exclude(pk=profile.pk).exists():
            candidate = f"{base}-{suffix}"
            suffix += 1
        profile.slug = candidate
        profile.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_account_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True, null=True),
        ),
        migrations.RunPython(fill_profile_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
