# Generated by Django 5.2.11 on 2026-03-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_managers_and_more'),
        ('users', '0007_userprofile_slug'),
    ]

    operations = [
    ]
