# Generated by Django 5.2.11 on 2026-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['route', 'expires_at'], name='idem_route_expires_idx'),
        ),
    ]
